### ISSUE TITLE
SSLError in kojid when accessing koji-hub host from koji-builder

### ISSUE THREAD

**Issue by alcm-b** [release-engineering/koji-dojo#28]
kojid fails to start in koji-builder container:

```
+ start_builder RUN_IN_FOREGROUND
+ local RUN_IN_FOREGROUND=RUN_IN_FOREGROUND
+ echo 'Starting koji builder on 172.17.0.4'
Starting koji builder on 172.17.0.4
+ '[' RUN_IN_FOREGROUND == RUN_IN_FOREGROUND ']'
+ /usr/sbin/kojid -d -v -f --force-lock
Traceback (most recent call last):
  File "/usr/sbin/kojid", line 5124, in <module>
    options.serverca)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2199, in ssl_login
    sinfo = self.callMethod('sslLogin', proxyuser)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2247, in callMethod
    return self._callMethod(name, args, opts)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2364, in _callMethod
    return self._sendCall(handler, headers, request)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2278, in _sendCall
    return self._sendOneCall(handler, headers, request)
  File "/usr/lib/python2.7/site-packages/koji/__init__.py", line 2323, in _sendOneCall
    r = self.rsession.post(handler, **callopts)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 507, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'koji-hub' doesn't match either of 'localhost', '172.17.0.3'
```

The workaround is to replace hostname with koji-hub IP address:                                                 

```
sed -i 's|http://koji-hub|http://172.17.0.3|' builder/bin/entrypoint.sh
```

**Comment by jdcasey** [comment]
Did you use --link to connect them? If so, you should have been able to resolve the hub using something like --link koji-hub:koji-hub in the run command for the builder.

**Comment by alcm-b** [comment]
I followed the README.md, so I ran ./builder/docker-scripts/build-all.sh →./builder/docker-scripts/run-all.sh , and the latter has '--link' options for koji-hub:

```
./builder/docker-scripts/run.sh:docker run --privileged=true -ti --name=koji-builder -v /opt/koji:/opt/koji -v /opt/koji-files:/mnt/koji --link koji-db --link koji-hub docker.io/buildchimp/koji-dojo-builder:dev
```

The rest of the '--link' options are:
```
$ grep link ./builder/docker-scripts/run*.sh
./builder/docker-scripts/run-all.sh:# docker run -ti --name=koji-hub -v /opt/koji-files:/mnt/koji -v /opt/koji:/opt/koji -v /opt/koji-clients:/opt/koji-clients --link koji-db:koji-db docker.io/buildchimp/koji-dojo-hub
./builder/docker-scripts/run-all.sh:docker run -d --name=koji-hub -v /opt/koji-files:/mnt/koji -v /opt/koji:/opt/koji -v /opt/koji-clients:/opt/koji-clients --link koji-db:koji-db docker.io/buildchimp/koji-dojo-hub:dev
./builder/docker-scripts/run.sh:#docker run --cap-add=SYS_ADMIN -ti --name=koji-builder -v /opt/koji-files:/mnt/koji --link koji-db --link koji-hub docker.io/buildchimp/koji-dojo-builder
./builder/docker-scripts/run.sh:docker run --privileged=true -ti --name=koji-builder -v /opt/koji:/opt/koji -v /opt/koji-files:/mnt/koji --link koji-db --link koji-hub docker.io/buildchimp/koji-dojo-builder:dev
```

**Comment by alcm-b** [comment]
Ah wait - is `--link koji-hub` the same as `--link koji-hub:koji-hub` ?

**Comment by jdcasey** [comment]
yeah, it should be the same.

**Comment by jdcasey** [comment]
Sorry, I think I lost track of this. Is this still happening?

**Comment by alcm-b** [comment]
Yes, I still can reproduce it. Apparently, it is this one described in Requests docs http://docs.python-requests.org/en/master/community/faq/#what-are-hostname-doesn-t-match-errors
